version: '3.8'

services:
  nodo1:
    build: .
    container_name: nodo1
    ports:
      - "8004:8000"
    environment:
      - NODE_ID=nodo1
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=true
      - APP_URL=http://localhost:8004
      - DB_CONNECTION=pgsql
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    networks:
      - blockchain-net

  nodo2:
    build: .
    container_name: nodo2
    ports:
      - "8002:8000"
    environment:
      - NODE_ID=nodo2
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=true
      - APP_URL=http://localhost:8002
      - DB_CONNECTION=pgsql
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    networks:
      - blockchain-net

  nodo3:
    build: .
    container_name: nodo3
    ports:
      - "8003:8000"
    environment:
      - NODE_ID=nodo3
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=true
      - APP_URL=http://localhost:8003
      - DB_CONNECTION=pgsql
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    networks:
      - blockchain-net

networks:
  blockchain-net:
    driver: bridge
